import Groq from "groq-sdk";
import dotenv from "dotenv";

dotenv.config();

export const ALLOWED_MODELS = [
  "llama-3.3-70b-versatile",
  "llama-3.1-8b-instant",
  "llama-3.1-70b-versatile",
  "qwen/qwen3.8-27b",
  "openai/gpt-oss-20b",
  "openai/gpt-oss-120b",
  "groq/compound-mini",
  "groq/compound"
];

export const DEFAULT_MODEL = "llama-3.3-70b-versatile";
export const FALLBACK_MODEL = "qwen/qwen3.8-27b";

export interface SessionContextData {
  sessionId?: string;
  jobTitle?: string;
  job_title?: string;
  company?: string;
  experienceLevel?: string;
  experience_level?: string;
  interviewRound?: string;
  interview_round?: string;
  streamingModel?: string;
  streaming_model?: string;
  notes?: string;
  resumeText?: string;
  resume_text?: string;
  language?: string;
  source?: string;
}

export interface ChatStreamOptions {
  messages: Array<{ role: "system" | "user" | "assistant"; content: any }>;
  model?: string;
  apiKey?: string;
  sessionContext?: SessionContextData;
  signal?: AbortSignal;
  onChunk?: (chunkText: string) => void;
}

export interface ScreenAnalysisOptions {
  imageBase64: string;
  question?: string;
  model?: string;
  apiKey?: string;
  sessionContext?: SessionContextData;
  signal?: AbortSignal;
  onChunk?: (chunkText: string) => void;
}

export class GroqBackendService {
  private client: Groq | null = null;

  constructor() {
    this.initClient();
  }

  private initClient(): void {
    const apiKey = process.env.GROQ_API_KEY;
    if (apiKey) {
      this.client = new Groq({ apiKey });
    }
  }

  private getClient(apiKeyOverride?: string): Groq {
    if (apiKeyOverride && apiKeyOverride.trim().length > 0) {
      return new Groq({ apiKey: apiKeyOverride.trim() });
    }
    if (!this.client) {
      this.initClient();
    }
    if (!this.client) {
      throw new Error("Groq client not initialized. Check GROQ_API_KEY in backend environment.");
    }
    return this.client;
  }

  public isConfigured(): boolean {
    return !!process.env.GROQ_API_KEY;
  }

  public resolveModel(requestedModel?: string): string {
    if (!requestedModel) return DEFAULT_MODEL;
    if (ALLOWED_MODELS.includes(requestedModel)) return requestedModel;
    return DEFAULT_MODEL;
  }

  public buildSystemPrompt(context?: SessionContextData): string {
    const jobTitle = context?.jobTitle || context?.job_title || "Software Engineer";
    const company = context?.company ? ` at ${context.company}` : "";
    const experienceLevel = context?.experienceLevel || context?.experience_level || "mid-level";
    const interviewRound = context?.interviewRound || context?.interview_round || "technical";

    let prompt = `You are the candidate in a live job interview for a ${experienceLevel} ${jobTitle}${company} (${interviewRound} round).
You are answering the interviewer's questions in real time. Your job is to give sharp, genuine, on-point interview answers — the kind a strong candidate gives to get hired, not textbook filler.

ANSWER FRAMEWORKS — use the right one for each question type:

1. BEHAVIORAL ("Tell me about a time...", "How did you handle..."): Use STAR — 1 sentence each for Situation, Task, Action, and Result. Keep it real and specific. Total: 4-5 sentences.
2. TECHNICAL ("How does X work?", "What is Y?", "Explain Z"): Give the direct concept in 1-2 sentences, then a real-world application or comparison in 1-2 sentences. No fluff.
3. SYSTEM DESIGN ("Design a...", "How would you architect..."): Give 2-3 clear design decisions with brief justifications. Mention trade-offs.
4. CODING PROBLEM: Briefly explain your approach in 1 sentence, then write clean minimal code.
5. INTRO / "Tell me about yourself": 3-sentence structure — who you are + what you do + what you're looking for. Confident, not a resume recitation.
6. OPINION / SITUATIONAL ("What would you do if..."): Give a direct opinion/decision first, then explain why in 1-2 sentences.

MANDATORY RULES:
1. Answer in FIRST PERSON ("I", "my", "we") — you ARE the candidate.
2. NO bullet points, NO numbered lists, NO markdown headers. Speak naturally as if talking aloud.
3. NO greetings, NO filler phrases like "Great question!", "Sure!", "That's a great point". Start with the actual answer immediately.
4. NEVER fabricate jobs, companies, or experiences not in the resume. If the resume has real experience, use it. If not, speak in general engineering terms ("In my experience..." or "When I've worked on similar problems...").
5. Keep answers TIGHT — 3 to 6 sentences max for most questions. Interview time is limited.
6. Sound confident and direct, like someone who knows their stuff. Not nervous, not over-explaining.
7. For yes/no questions, answer yes or no FIRST, then explain briefly.
8. STT ROBUSTNESS: Transcripts are generated by live speech-to-text and may contain slight phonetic misrecognitions of technical jargon (e.g., 'state' instead of 'set', 'table' instead of 'tuple', 'sink' instead of 'sync', 'py torch' instead of 'PyTorch', 'dunder' instead of '__dunder__', 'fast api' instead of 'FastAPI', 'spring boot' instead of 'Spring Boot', 's three' instead of 'S3', 'e c two' instead of 'EC2'). Intelligently infer the interviewer's intended technical question from context across all fields (Python, FastAPI, Django, Flask, Data Science, AI/ML, Data Analysis, AWS, System Design, Java, Spring Boot, Networking, SQL, DSA, HR behavioral) and answer the true concept directly without pointing out the transcript glitch.`;

    if (context) {
      const resume = context.resumeText || context.resume_text;
      if (resume) {
        prompt += `\n\nCANDIDATE'S ACTUAL BACKGROUND (use this for specific answers):\n${resume.slice(0, 2000)}`;
      }
      if (context.notes) {
        prompt += `\n\nFOCUS AREAS / EXTRA CONTEXT:\n${context.notes.slice(0, 800)}`;
      }
    }

    prompt += `\n\nRemember: Real, concise, confident. No fake experiences. No padding. Answer like a senior engineer who has done this before.`;

    return prompt;
  }

  /**
   * Stream a chat completion from Groq API.
   */
  public async streamChat(
    options: ChatStreamOptions,
    onChunk: (chunk: string) => void
  ): Promise<{ fullAnswer: string; modelUsed: string }> {
    const client = this.getClient(options.apiKey);

    const targetModel = this.resolveModel(options.model);
    const systemPrompt = this.buildSystemPrompt(options.sessionContext);
    
    // Check if system prompt is already in messages, otherwise prepend
    const hasSystemMsg = options.messages.some((m) => m.role === "system");
    const fullMessages = hasSystemMsg
      ? options.messages
      : [{ role: "system" as const, content: systemPrompt }, ...options.messages];

    let stream: any;
    let modelUsed = targetModel;

    try {
      stream = await client.chat.completions.create(
        {
          model: targetModel,
          messages: fullMessages,
          max_tokens: 450,
          temperature: 0.55,
          stream: true,
        },
        { signal: options.signal }
      );
    } catch (err: any) {
      // Fallback model handling on 404 or specific model rate limits
      if (
        (err?.status === 404 || err?.message?.includes("does not exist") || err?.status === 429) &&
        targetModel !== FALLBACK_MODEL
      ) {
        modelUsed = FALLBACK_MODEL;
        stream = await client.chat.completions.create(
          {
            model: FALLBACK_MODEL,
            messages: fullMessages,
            max_tokens: 350,
            temperature: 0.6,
            stream: true,
          },
          { signal: options.signal }
        );
      } else {
        throw err;
      }
    }

    let fullAnswer = "";
    for await (const chunk of stream) {
      const delta = chunk.choices[0]?.delta?.content;
      if (delta) {
        fullAnswer += delta;
        onChunk(delta);
      }
    }

    return { fullAnswer, modelUsed };
  }

  /**
   * Stream screen / vision analysis from Groq API.
   */
  public async streamScreenAnalysis(
    options: ScreenAnalysisOptions,
    onChunk: (chunk: string) => void
  ): Promise<{ fullAnswer: string; modelUsed: string }> {
    const client = this.getClient(options.apiKey);

    const targetModel = options.model || "llama-3.2-11b-vision-preview";
    const questionText =
      options.question ||
      "Analyze what is shown on this screen and provide key technical insights or interview answers.";

    try {
      const stream = await client.chat.completions.create(
        {
          model: targetModel,
          messages: [
            {
              role: "user",
              content: [
                { type: "text", text: questionText },
                {
                  type: "image_url",
                  image_url: {
                    url: `data:image/jpeg;base64,${options.imageBase64}`,
                  },
                },
              ] as any,
            },
          ],
          max_tokens: 350,
          stream: true,
        },
        { signal: options.signal }
      );

      let fullAnswer = "";
      for await (const chunk of stream) {
        const delta = chunk.choices[0]?.delta?.content;
        if (delta) {
          fullAnswer += delta;
          onChunk(delta);
        }
      }

      return { fullAnswer, modelUsed: targetModel };
    } catch (err: any) {
      // Graceful fallback notice for models/keys without vision support
      const notice =
        "*(Screen captured)* Screen analysis requires a vision-enabled model on your Groq project. Use voice or manual questions for instant answers.";
      onChunk(notice);
      return { fullAnswer: notice, modelUsed: "fallback-notice" };
    }
  }
}

export const groqBackendService = new GroqBackendService();

